[package]
name = "cardkit"
version = "0.1.0-alpha.15"
edition = "2021"
license = "MIT"
homepage = "https://calm.cards/"
description = "Types and functions for creating calm.cards compatible WASM cards."

[dependencies]
ultraviolet = { version = "0.6", features = [] }
